export const DEMO_TEAM = {
	id: "seed-team-northwind",
	name: "Northwind Sales",
} as const;

export const DEMO_ACCOUNTS = [
	{
		key: "admin",
		name: "Alex Admin",
		email: "admin@example.test",
		password: "DemoAdmin123!",
		role: "administrator" as const,
		teamId: null,
	},
	{
		key: "manager",
		name: "Morgan Manager",
		email: "manager@example.test",
		password: "DemoManager123!",
		role: "sales_manager" as const,
		teamId: DEMO_TEAM.id,
	},
	{
		key: "rep",
		name: "Riley Rep",
		email: "rep@example.test",
		password: "DemoRep123!",
		role: "sales_representative" as const,
		teamId: DEMO_TEAM.id,
	},
] as const;

export type DemoAccountKey = (typeof DEMO_ACCOUNTS)[number]["key"];

export const DEMO_COMPANIES = [
	{
		id: "seed-company-acme",
		name: "Acme Analytics",
		domain: "acmeanalytics.test",
		industry: "SaaS",
		size: "smb" as const,
		status: "active" as const,
		ownerKey: "rep" as const,
		notes: "Strong product fit for analytics upsell.",
	},
	{
		id: "seed-company-brightline",
		name: "Brightline Logistics",
		domain: "brightline.test",
		industry: "Logistics",
		size: "mid_market" as const,
		status: "prospect" as const,
		ownerKey: "rep" as const,
		notes: "Pilot opportunity for fleet visibility.",
	},
	{
		id: "seed-company-cedar",
		name: "Cedar Systems",
		domain: "cedarsystems.test",
		industry: "Infrastructure",
		size: "enterprise" as const,
		status: "active" as const,
		ownerKey: "manager" as const,
		notes: "Enterprise renewal cycle in Q3.",
	},
	{
		id: "seed-company-delta",
		name: "Delta Manufacturing",
		domain: "delta-mfg.test",
		industry: "Manufacturing",
		size: "smb" as const,
		status: "prospect" as const,
		ownerKey: "rep" as const,
		notes: "Inbound lead from trade show.",
	},
] as const;

export const DEMO_CONTACTS = [
	{
		id: "seed-contact-acme-1",
		companyId: "seed-company-acme",
		firstName: "Jordan",
		lastName: "Lee",
		title: "VP Operations",
		email: "jordan.lee@acmeanalytics.test",
		phone: "+1-555-0101",
		ownerKey: "rep" as const,
	},
	{
		id: "seed-contact-acme-2",
		companyId: "seed-company-acme",
		firstName: "Sam",
		lastName: "Patel",
		title: "Director of IT",
		email: "sam.patel@acmeanalytics.test",
		phone: "+1-555-0102",
		ownerKey: "rep" as const,
	},
	{
		id: "seed-contact-brightline-1",
		companyId: "seed-company-brightline",
		firstName: "Casey",
		lastName: "Nguyen",
		title: "Head of Fleet",
		email: "casey.nguyen@brightline.test",
		phone: "+1-555-0201",
		ownerKey: "rep" as const,
	},
	{
		id: "seed-contact-cedar-1",
		companyId: "seed-company-cedar",
		firstName: "Taylor",
		lastName: "Brooks",
		title: "Procurement Lead",
		email: "taylor.brooks@cedarsystems.test",
		phone: "+1-555-0301",
		ownerKey: "manager" as const,
	},
	{
		id: "seed-contact-delta-1",
		companyId: "seed-company-delta",
		firstName: "Jamie",
		lastName: "Reed",
		title: "Plant Manager",
		email: "jamie.reed@delta-mfg.test",
		phone: "+1-555-0401",
		ownerKey: "rep" as const,
	},
] as const;

export const DEMO_DEALS = [
	{
		id: "seed-deal-acme-expansion",
		companyId: "seed-company-acme",
		ownerKey: "rep" as const,
		title: "Analytics Platform Expansion",
		valueCents: 4_500_000,
		stage: "qualified" as const,
		probability: 55,
		expectedCloseDate: "2026-08-15",
		contactIds: ["seed-contact-acme-1"],
	},
	{
		id: "seed-deal-acme-renewal",
		companyId: "seed-company-acme",
		ownerKey: "rep" as const,
		title: "Support Renewal",
		valueCents: 1_200_000,
		stage: "closed_won" as const,
		probability: 100,
		expectedCloseDate: "2026-06-01",
		closedAt: "2026-06-01T16:00:00.000Z",
		contactIds: ["seed-contact-acme-2"],
	},
	{
		id: "seed-deal-brightline-pilot",
		companyId: "seed-company-brightline",
		ownerKey: "rep" as const,
		title: "Fleet Tracking Pilot",
		valueCents: 7_800_000,
		stage: "proposal" as const,
		probability: 40,
		expectedCloseDate: "2026-09-30",
		contactIds: ["seed-contact-brightline-1"],
	},
	{
		id: "seed-deal-cedar-license",
		companyId: "seed-company-cedar",
		ownerKey: "manager" as const,
		title: "Enterprise License",
		valueCents: 24_000_000,
		stage: "negotiation" as const,
		probability: 70,
		expectedCloseDate: "2026-07-31",
		contactIds: ["seed-contact-cedar-1"],
	},
	{
		id: "seed-deal-delta-discovery",
		companyId: "seed-company-delta",
		ownerKey: "rep" as const,
		title: "Initial Discovery",
		valueCents: 3_500_000,
		stage: "prospecting" as const,
		probability: 15,
		expectedCloseDate: "2026-10-15",
		contactIds: ["seed-contact-delta-1"],
	},
] as const;

export const DEMO_TASKS = [
	{
		id: "seed-task-followup-brightline",
		title: "Send pilot pricing options",
		description: "Share tiered pilot pricing with Casey.",
		assigneeKey: "rep" as const,
		relatedDealId: "seed-deal-brightline-pilot",
		relatedCompanyId: "seed-company-brightline",
		relatedContactId: "seed-contact-brightline-1",
		dueDate: "2026-07-18",
		priority: "high" as const,
		status: "open" as const,
	},
	{
		id: "seed-task-acme-demo",
		title: "Schedule expansion demo",
		description: "Book technical demo with Jordan.",
		assigneeKey: "rep" as const,
		relatedDealId: "seed-deal-acme-expansion",
		relatedCompanyId: "seed-company-acme",
		relatedContactId: "seed-contact-acme-1",
		dueDate: "2026-07-14",
		priority: "medium" as const,
		status: "open" as const,
	},
	{
		id: "seed-task-cedar-contract",
		title: "Review enterprise contract redlines",
		assigneeKey: "manager" as const,
		relatedDealId: "seed-deal-cedar-license",
		relatedCompanyId: "seed-company-cedar",
		relatedContactId: "seed-contact-cedar-1",
		dueDate: "2026-07-12",
		priority: "high" as const,
		status: "completed" as const,
		completedAt: "2026-07-10T14:30:00.000Z",
	},
	{
		id: "seed-task-delta-intro",
		title: "Send intro deck to Jamie",
		assigneeKey: "rep" as const,
		relatedCompanyId: "seed-company-delta",
		relatedContactId: "seed-contact-delta-1",
		dueDate: "2026-07-16",
		priority: "low" as const,
		status: "open" as const,
	},
] as const;

export const DEMO_ACTIVITIES = [
	{
		id: "seed-activity-acme-note",
		type: "note" as const,
		subject: "Expansion requirements captured",
		body: "Jordan confirmed need for additional seats and SSO.",
		actorKey: "rep" as const,
		relatedCompanyId: "seed-company-acme",
		relatedContactId: "seed-contact-acme-1",
		relatedDealId: "seed-deal-acme-expansion",
		occurredAt: "2026-07-08T10:00:00.000Z",
	},
	{
		id: "seed-activity-brightline-call",
		type: "call" as const,
		subject: "Pilot scope call",
		body: "Discussed rollout timeline and success metrics.",
		actorKey: "rep" as const,
		relatedCompanyId: "seed-company-brightline",
		relatedContactId: "seed-contact-brightline-1",
		relatedDealId: "seed-deal-brightline-pilot",
		occurredAt: "2026-07-09T15:30:00.000Z",
	},
	{
		id: "seed-activity-acme-stage",
		type: "stage_change" as const,
		subject: "Deal moved to qualified",
		body: "Expansion opportunity validated by finance.",
		actorKey: "rep" as const,
		relatedDealId: "seed-deal-acme-expansion",
		relatedCompanyId: "seed-company-acme",
		occurredAt: "2026-07-07T09:15:00.000Z",
	},
	{
		id: "seed-activity-cedar-meeting",
		type: "meeting" as const,
		subject: "Enterprise pricing review",
		body: "Legal and procurement aligned on term length.",
		actorKey: "manager" as const,
		relatedCompanyId: "seed-company-cedar",
		relatedContactId: "seed-contact-cedar-1",
		relatedDealId: "seed-deal-cedar-license",
		occurredAt: "2026-07-06T13:00:00.000Z",
	},
	{
		id: "seed-activity-task-complete",
		type: "task_completed" as const,
		subject: "Task completed: Review enterprise contract redlines",
		actorKey: "manager" as const,
		relatedDealId: "seed-deal-cedar-license",
		relatedCompanyId: "seed-company-cedar",
		occurredAt: "2026-07-10T14:30:00.000Z",
	},
] as const;

export function getSeedSummary() {
	return {
		teams: 1,
		accounts: DEMO_ACCOUNTS.length,
		companies: DEMO_COMPANIES.length,
		contacts: DEMO_CONTACTS.length,
		deals: DEMO_DEALS.length,
		tasks: DEMO_TASKS.length,
		activities: DEMO_ACTIVITIES.length,
	};
}
